# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94340d54b7d6ceb8f82663681a2ae676548939f19693747e8c7df3e663a92fa2a577335d2b9b34ed83027dc236e17208c19d095a53112848953565393cd6f48f

test:
  secret_key_base: 736c66d32293f12d2fe34ccbd30e1fb24a5aa914c00e15355767d8cc1881e71f85823a5942e681e22c2538db3f4d0913114404ab4910b87d494c86347dd5bfc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
